name: ROS2 CI with Docker

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-22.04  # The host runs Ubuntu, but...
    container: osrf/ros:jazzy-desktop-full  # 👈 This is the Docker container where your build runs

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install tools
      run: |
        apt update && apt install -y \
          python3-colcon-common-extensions \
          python3-pip git curl
        pip3 install -U vcstool autopep8 --break-system-packages

    - name: Install dependencies
      shell: bash
      run: |
        source /opt/ros/jazzy/setup.bash
        rosdep update
        rosdep install --from-paths src --ignore-src -r -y

    - name: Build packages
      shell: bash
      run: |
        source /opt/ros/jazzy/setup.bash
        colcon build --event-handlers console_cohesion+

    - name: Run tests
      shell: bash
      run: |
        source /opt/ros/jazzy/setup.bash
        colcon test
        colcon test-result --verbose
