name: ROS2 CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup ROS 2 Jazzy
      uses: ros-tooling/setup-ros@v0.6
      with:
        distribution: jazzy

    - name: Install dependencies
      run: |
        sudo apt update
        rosdep update
        rosdep install --from-paths src --ignore-src -r -y

    - name: Build workspace
      run: |
        source /opt/ros/jazzy/setup.bash
        colcon build --event-handlers console_cohesion+

    - name: Run tests
      run: |
        source /opt/ros/jazzy/setup.bash
        colcon test
        colcon test-result --verbose
